<a href="https://colab.research.google.com/github/Sasha1095/Task4/blob/master/%D0%9D%D0%98%D0%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.linalg
import math

In [ ]:
def HtoG(H):
    """Convert a Parity Check Matrix in systematic form to a Generator Matrix.
    Args:
        H: Parity Check Matrix in systematic form
    Returns:
        Generator Matrix G
    """
    n = np.shape(H)[1]
    k = n - np.shape(H)[0]
    P = HtoP(H)
    Ik = np.eye(k)
    G = np.concatenate((P, Ik), axis=1)
    return G.astype(int)
def HtoP(H):
    """Extract the submatrix P from a Parity Check Matrix in systematic form.
    Args:
        H: Parity Check Matrix in systematic form
    Returns:
        Submatrix P of G.
    """
    n = np.shape(H)[1]
    k = n - np.shape(H)[0]
    PK = H[:, n - k:n]
    P = np.transpose(PK)
    return P.astype(int)


In [ ]:
H = np.array([[1, 1, 0, 1, 1, 0, 0, 1, 0, 0],
              [0, 1, 1, 0, 1, 1, 1, 0 ,0 ,0],
              [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
              [1, 1, 0, 0, 0, 1, 1, 0, 1, 0],
              [0, 0, 1, 0, 0, 1, 0, 1, 0, 1]])
print(HtoG(H))

[[0 1 0 1 1 1 0 0 0 0]
 [0 1 0 1 0 0 1 0 0 0]
 [1 0 1 0 1 0 0 1 0 0]
 [0 0 1 1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 1]]


In [ ]:
Htr = H.transpose()
print(Htr)

[[1 0 0 1 0]
 [1 1 0 1 0]
 [0 1 0 0 1]
 [1 0 1 0 0]
 [1 1 0 0 0]
 [0 1 0 1 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 0 1]]


In [5]:
Hempty = np.zeros((3,3))
Hempty[0][1] = 1
print(Hempty)

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
def FillMatrix(column, rows, H, stringOfData, hOfCirculant):
  ''' column - номер строки матрицы, rows - номер ряда матрицы
  stringOfData - данные первой строки, которые будут циклически передаваться
  H - матрица
  '''
  length = len(stringOfData)
  for j in range(hOfCirculant):
    for i in range(length):
      H[column + j][rows + (i+j)%length] = stringOfData[i]#stringOfData[(i + j)%length]
  return H

In [19]:
Hempty = np.zeros((3,3))
stringOfData = np.array([0,0,1])
FillMatrix(0, 0, Hempty, stringOfData, 3)
print(Hempty)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [22]:
Htest = np.zeros((3,3,3))
print(Htest)
print(Htest[0][0])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[0. 0. 0.]


In [17]:
def FillFullMatrix(AllData, H, hOfCirculant, x, y):
  '''
  AllData - трёмерный массив, в котором хранятся все данные для заполнения H
  x - количество двумерных массивов
  y количество строк в каждом массиве
  '''
  length = len((AllData[0][0]))
  h0 = 0
  for i in range(x):
    for j in range(y):
      FillMatrix(i*hOfCirculant, j*length, H, AllData[i][j],hOfCirculant)
  return H

In [18]:
H = np.zeros((9,9), dtype = int)
AllData = np.zeros((3,3,3))
AllData[0][0][0]= 1
AllData[0][1][0]= 1
AllData[0][2][0]= 1
AllData[1][0][1]= 1
AllData[1][1][1]= 1
AllData[1][2][1]= 1
AllData[2][0][2]= 1
AllData[2][1][2]= 1
AllData[2][2][2]= 1
print((H[0][0]))
FillFullMatrix(AllData, H, 3, 3, 3)
print(H)

0
[[1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]]
